import Head from 'next/head';
import React from 'react';
import { BlogLayout } from 'layouts/blog';
import Navbar from '../../components/blog-navbar';

const Blog: React.FC = () => (
  <div>
    <Head>
      <title>Blog</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <BlogLayout>
      <Navbar />
    </BlogLayout>
  </div>
);

export default Blog;
